### PR TITLE
[WIP] initial build script for osx

### PR DESCRIPTION
**Pull request by nickdesaulniers**
still not fully complete, but starting on a build script for osx

mainly, a source/osx/main.c needs to be written, which is the hard part, since there's no X11 on OSX.  I've used SDL2 in the past, but now might be the time for me to dig into Cocoa.

### CODE REVIEW

**Comment by nsenica** [comment]
You can install XQuartz and it will provide X11. I managed to make it compile and run with some changes and by copying the linux main.c, but something went wrong with the display the main loop works but there's no output, apart from that it seems to be working fine.

**Comment by nsenica** [comment]
I managed to make it work with X11 from inside XQuartz. :) 
Here's the diff, apart from that just copy source/linux/main.c into source/osx/main.c and it will work.

```
diff --git a/Makefile.osx b/Makefile.osx
index 6304001..06fa2b4 100644
--- a/Makefile.osx
+++ b/Makefile.osx
@@ -1,8 +1,8 @@
 CC     :=  clang
 SDIR   :=  source
-IDIR   :=  -Iinclude
+IDIR   :=  -Iinclude -I/usr/X11/include
 CFLAGS :=  $(IDIR) -Wall -fms-extensions -Ofast -Wno-microsoft
-LFLAGS :=  -framework OpenGL
+LFLAGS :=  -L/usr/X11/lib -lX11 -lGL
 ODIR   :=  lbuild
 CFILES :=  $(wildcard $(SDIR)/*.c)
 CFILES :=  $(CFILES) $(wildcard $(SDIR)/osx/*.c)
diff --git a/include/main.h b/include/main.h
index c84ee12..7375d76 100644
--- a/include/main.h
+++ b/include/main.h
@@ -9,7 +9,7 @@ void quit(void);
    LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam);
 #endif

-#ifdef LIN
+#if defined LIN || defined __APPLE__
    extern Display *dpy;
    extern Window root;
    extern GLint att[];
diff --git a/include/platform.h b/include/platform.h
index 297939e..f6b8c4e 100644
--- a/include/platform.h
+++ b/include/platform.h
@@ -31,12 +31,12 @@
    #define LITTLE_E
 #endif

-#ifdef __APPLE__
+#ifdef __APPLE__Aaa
 #include <OpenGL/gl.h>
 #define LITTLE_E
 #endif

-#ifdef LIN
+#if defined LIN || defined __APPLE__
    #include <GL/gl.h>
    #include <GL/glx.h>
    #include <GL/glu.h>
diff --git a/source/display.c b/source/display.c
index 456da2a..b174a38 100644
--- a/source/display.c
+++ b/source/display.c
@@ -1,4 +1,4 @@
-#ifdef LIN
+#if defined LIN || defined __APPLE__
    #include <time.h>
    #include <unistd.h>
 #endif
@@ -15,11 +15,11 @@
    unsigned int *framebuffer = NULL;
 #endif

-#if defined WIN || defined LIN
+#if defined WIN || defined LIN || defined __APPLE__
    COLOUR framebuffer[160 * 144];
 #endif

-#if defined WIN || defined LIN || defined DS3
+#if defined WIN || defined LIN || defined DS3 || defined __APPLE__
    const COLOUR palette[4] = {
        { 255, 255, 255 },
        { 192, 192, 192 },
@@ -83,7 +83,7 @@ void renderScanline(void) {
    int y = (gpu.scanline + gpu.scrollY) & 7;

    int pixelOffset;
-   #if defined WIN || defined LIN || defined PS4
+   #if defined WIN || defined LIN || defined PS4 || defined __APPLE__
        pixelOffset = gpu.scanline * 160;
    #endif

@@ -111,7 +111,7 @@ void renderScanline(void) {

        scanlineRow[i] = colour;

-       #if defined WIN || defined LIN
+       #if defined WIN || defined LIN || defined __APPLE__
            framebuffer[pixelOffset].r = backgroundPalette[colour].r;
            framebuffer[pixelOffset].g = backgroundPalette[colour].g;
            framebuffer[pixelOffset].b = backgroundPalette[colour].b;
@@ -162,7 +162,7 @@ void renderScanline(void) {
            COLOUR *pal = spritePalette[sprite.palette];

            int pixelOffset;
-           #if defined WIN || defined LIN || defined PS4
+           #if defined WIN || defined LIN || defined PS4 || defined __APPLE__
                pixelOffset = gpu.scanline * 160 + sx;
            #endif

@@ -191,7 +191,7 @@ void renderScanline(void) {
                    else colour = tiles[sprite.tile][tileRow][x];

                    if(colour) {
-                       #if defined WIN || defined LIN
+                       #if defined WIN || defined LIN || defined __APPLE__
                            framebuffer[pixelOffset].r = pal[colour].r;
                            framebuffer[pixelOffset].g = pal[colour].g;
                            framebuffer[pixelOffset].b = pal[colour].b;
@@ -243,7 +243,7 @@ void copyMap(void) {
 }
 #endif

-#if defined WIN || defined LIN
+#if defined WIN || defined LIN || defined __APPLE__
 void drawFramebuffer(void) {
    // Should render to a texture instead of obsolete glDrawPixels

@@ -264,9 +264,10 @@ void drawFramebuffer(void) {
        #endif
    #endif

-   #ifdef LIN
+   #if defined LIN || defined __APPLE__
        glXSwapBuffers(dpy, win);

+#if 0
        #ifndef DEBUG_SPEED
            static struct timespec frameStart;
            struct timespec frameEnd;
@@ -283,6 +284,7 @@ void drawFramebuffer(void) {

            clock_gettime(CLOCK_MONOTONIC, &frameStart);
        #endif
+#endif
    #endif
 }
 #endif
diff --git a/source/interrupts.c b/source/interrupts.c
index b38c2e3..da2fb80 100644
--- a/source/interrupts.c
+++ b/source/interrupts.c
@@ -91,7 +91,7 @@ void vblank(void) {
        if(!aptMainLoop() || ((kHeld & KEY_START) && (kHeld & KEY_SELECT) && (kHeld & KEY_L) && (kHeld & KEY_R))) quit();
    #endif

-   #ifdef LIN
+   #if defined LIN || defined __APPLE__
        drawFramebuffer();
    #endif
```

**Comment by CTurt** [comment]
Great work porting this to OS X, please can you make a full pull request so it is easy to merge? Thanks.

**Comment by nickdesaulniers** [comment]
watch out, in the patch I spotted:

```
-#ifdef __APPLE__
+#ifdef __APPLE__Aaa
```

I think that's a typo

**Comment by nsenica** [comment]
Actually that's not a typo, it was intended to not let the compiler go through that and use the system OpenGL but instead use the ones defined afterwards which belong to X11. That section can be safely removed from this version, it was not supposed to be in the final patch.

@nickdesaulniers are you merging this into your fork and then make the pull request ? or do you prefer that I do it ?

I'm planning to create a Cocoa window so we don't need X11, this is something I'll have to learn from scratch, but it will be fun.

**Comment by nickdesaulniers** [comment]
No, you can send the PR and I'll close this one.

**Pull request closed without merging**
